# Generated by Django 3.1.7 on 2021-03-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyrocketSql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=1000)),
            ],
        ),
    ]
